# 1. print list of students  
puts "----------------------------------------"
puts "Makers Academy - January Cohort Students"
puts "----------------------------------------"
puts "Nabin Rai"
puts "Biwek Shrestha"
puts "Andrey"
puts "Makis Otman"
puts "James Hunter"
puts "Roy"
puts "Peter"
puts "Jorja"
puts "Rolando"
puts "Abraham Thomas"
puts "Berta Gutierrez"
puts "Ayaz"
# 3. Then we print the overall number of students
print "Overall we have 12 "
puts "students"