puts "----------------------------------------"
puts "Makers Academy - January Cohort Students"
puts "----------------------------------------"
puts "Nabin Rai"
puts "Biwek Shrestha"
puts "Andrey"
puts "Makis Otman"
puts "James Hunter"
puts "Roy"
puts "Peter"
puts "Jorja"
puts "Rolando"
puts "Abraham Thomas"
puts "Berta Gutierrez"
puts "Ayaz"